export const scriptCategories = [
  { id: "combat", name: "Combat" },
  { id: "utility", name: "Utility" },
  { id: "gui", name: "GUI" },
  { id: "admin", name: "Admin" },
  { id: "trolling", name: "Trolling" },
  { id: "simulator", name: "Simulator" },
  { id: "tycoon", name: "Tycoon" },
  { id: "fps", name: "FPS" },
  { id: "rpg", name: "RPG" },
  { id: "adventure", name: "Adventure" },
  { id: "racing", name: "Racing" },
  { id: "horror", name: "Horror" },
  { id: "misc", name: "Miscellaneous" },
]
